# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/convert
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="files"; filename="small.RAW"
Content-Type: application/octet-stream

< ./small.RAW
--boundary--